Lesson2/Web1/Models/ErrorViewModel.cs
namespace Web1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lesson2/Web1/Controllers/GreenwichController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web1.Controllers
{
    public class GreenwichController : Controller
    {
        public IActionResult Index()
        {
            //pass data from Controller (Backend) to View (Frontend)

            int year = DateTime.Now.Year;
            string university = "Greenwich Vietnam";
            string[] sports = ["Football", "Volleyball", "Badminton", "Pickle ball"];
            int[] numbers = [10, 30, 49, 28, 18, 79];

            //method 1: ViewBag
            ViewBag.Year = year;
            ViewBag.DaiHoc = university;
            ViewBag.ThanhPho = "Hà Nội";
            ViewBag.Sports = sports;
            ViewBag.Numbers = numbers;

            //method 2: ViewData
            ViewData["PiNumber"] = 3.14;
            ViewData["Pass"] = true;
  
            return View();
        }
    }
}

Lesson2/Web1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web1.Models;

namespace Web1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        //default url: localhost:PORT/Home/About
        //set custom route (url)
        [Route("/aboutus")]
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Demo()
        {
            //default view: Views/Home/Demo.cshtml
            //set custom view
            return View("~/Views/Demo/Test.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lesson2/Web1/Controllers/MobileController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web1.Controllers
{
    public class MobileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IPhone()
        {
            return View();
        }

        public IActionResult Samsung()
        {
            return View();
        }
    }
}

Lesson2/Web1/Views/Greenwich/Index.cshtml
<h1>The current year is @ViewBag.Year </h1>
<h2>We are studying in @ViewBag.DaiHoc</h2>
<h3>We are living in @ViewBag.ThanhPho </h3>
<h4>Pi Number = @ViewData["PiNumber"]</h4>
<h5>Pass exam : @ViewData["Pass"]</h5>

@{
    foreach (string sport in ViewBag.Sports)
    {
        <p>@sport</p>
    }
}

@foreach (var n in @ViewBag.Numbers)
{
    <h6>@n</h6>
}

@{
    var a = 5;
    var b = 10;
    var c = a + b;
    var comparison = "";
    if (a > b)
    {
        comparison = "a is greater than b";
    } else if (a < b)
    {
        comparison = "a is smaller than b";
    } else
    {
        comparison = "a is equal to b";
    }
}
<h5>c = @c</h5>
<h5>@comparison</h5>

Lesson2/Web1/Views/Mobile/Index.cshtml
<ol>
    <li>
        <a asp-controller="Mobile" asp-action="Iphone">
            <img src="https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/_/t_m_17.png" />
        </a>
    </li>
    <li>
        <a href="/Mobile/Samsung">
            <img src="https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/s/ss-s24-ultra-xam-222.png" />
        </a>
    </li>
</ol>

Lesson2/Web1/Views/Mobile/Iphone.cshtml
<iframe width="560" height="315" src="https://www.youtube.com/embed/GDlkCkcIqTs?si=Tvz7ezwIfhmcAfYz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

Lesson2/Web1/Views/Mobile/Samsung.cshtml
<iframe width="560" height="315" src="https://www.youtube.com/embed/BYRFUI3l5bo?si=7x80ykKR25Ob8oFf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

Lesson2/Web1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AMD201</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-uppercase" href="/Mobile">Mobile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" href="/Home/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Greenwich">Greenwich</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>